apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/ravindra-ui/nginx-argocd.git
    targetRevision: main
    path: .
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
